# .streamlit/secrets.toml
# Copy this template and fill in your actual values

[google]
client_id = "your-google-client-id.apps.googleusercontent.com"
client_secret = "your-google-client-secret"
redirect_uri = "https://your-app-name.streamlit.app"  # For production
# redirect_uri = "http://localhost:8501"  # For local development
